"""建图模块配置 — 从 config.settings 读取"""

# LLM
LLM_MODEL = "qwen3.5-flash"

# Embedding
EMBEDDING_MODEL = "text-embedding-v4"
EMBEDDING_DIMENSIONS = 768
EMBEDDING_ENCODING_FORMAT = "float"

# Concurrency
MAX_CONCURRENT = 5

# UMAP 全局
UMAP_GLOBAL_N_NEIGHBORS = 10
UMAP_GLOBAL_MIN_DIST = 0.0
UMAP_GLOBAL_METRIC = "cosine"
UMAP_GLOBAL_N_COMPONENTS = 30

# UMAP 分裂
UMAP_SPLIT_N_NEIGHBORS = 8
UMAP_SPLIT_N_COMPONENTS = 2

# HDBSCAN 初始
HDBSCAN_MIN_CLUSTER_SIZE = 5
HDBSCAN_MIN_SAMPLES = 1
HDBSCAN_METRIC = "euclidean"

# HDBSCAN 分裂
HDBSCAN_SPLIT_MIN_CLUSTER_SIZE = 5
HDBSCAN_SPLIT_MIN_SAMPLES = 2

# 模型持久化
MODEL_DIR = "src/graph/models"
UMAP_MODEL_FILE = "umap_global.pkl"

# LLM 采样
LLM_SAMPLE_THRESHOLD = 500
LLM_SAMPLE_SIZE = 500

# 阈值
MATCH_THRESHOLD = 0.6
DEDUP_THRESHOLD = 0.95
SPLIT_THRESHOLD = 100
MERGE_THRESHOLD_INNER = 0.85
MERGE_THRESHOLD_CROSS = 0.90
MAX_MEMBERSHIPS = 5
MIN_CLUSTER_SIZE = 5
BATCH_SIZE = 200
DETAINED_EXPIRE_DAYS = 14
